### ISSUE TITLE
Exception on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#117] opened 2017-07-12 10:41 UTC
When I try to load the attached file, I get an error. This used to load fine.
[citrate-cycle-TCGA-cycle_KEGG.xml.txt](https://github.com/iVis-at-Bilkent/newt/files/1141701/citrate-cycle-TCGA-cycle_KEGG.xml.txt)

**Comment by royludo** [comment] 2017-07-12 13:33
I tracked this issue down, the error thrown is: 
`index.js:21 The style property shape-polygon-points: -374999.99988096993 is invalid`

The problematic element is a process with the id: `http___pathwaycommons_org_pc2_BiochemicalReaction_fba5d6458e8d59abe57d998d0798c1b4RIGHT_TO_LEFT`

This comes from some invalid port position calculation that happens on load, around here: https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbgnml-to-json-converter.js#L284

For some reason, the relativeXPos variable gets assigned this value: `0.000020000000006348273` which should be either 0 something like 10, -10... Further down the line, it is used for some other computation which leads to the aberrant `-374999.99988096993`.

This may also come from something in this function: https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/utilities/sbgnml-to-json-converter.js#L47, because it changes slightly the bbox coordinates from what is provided in the file.

But I'm not familiar with these port handling parts, @ugurdogrusoz I suggest @metincansiper should handle this.

**Comment by royludo** [comment] 2017-07-12 13:44
Actually this can be more easily reproduced and tested with this sbgn file:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sbgn xmlns="http://sbgn.org/libsbgn/0.2">
    <map language="process description">
	<glyph class="process" id="http___pathwaycommons_org_pc2_BiochemicalReaction_fba5d6458e8d59abe57d998d0798c1b4RIGHT_TO_LEFT">
            <bbox w="15.0" h="15.0" x="249.35158" y="160.9326"/>
            <port id="InputPort_http___pathwaycommons_org_pc2_BiochemicalReaction_fba5d6458e8d59abe57d998d0798c1b4RIGHT_TO_LEFT" x="256.8516" y="158.4326"/>
            <port id="OutputPort_http___pathwaycommons_org_pc2_BiochemicalReaction_fba5d6458e8d59abe57d998d0798c1b4RIGHT_TO_LEFT" x="256.8516" y="178.4326"/>
        </glyph>
    </map>
</sbgn>
```
It contains only the specific problematic glyph.

**Comment by metincansiper** [comment] 2017-07-17 13:04
@ugurdogrusoz while re-designing port support, so that we will represent nodes which can have ports by polygons, we assumed that ports are vertically or horizontally aligned and they are not located inside node shape..

The ports in this example seems to be designed so that they have vertically aligned, but because of a calculation mistake in the file, relative 'x' values of the ports is not 0, but has a negligible value (While it is supposed to be 0 if there was no calculation mistake in the file).

Therefore, we attempt to render ports in horizontal order according to that negligable relative 'x' value instead of their relative 'y' value (It is because we determine the orientation by checking if that 'x' value is 0). However, as the ports seems to be inside node shape according to these 'x' values, we get the error.

I fixed this error by making an extra check. You can see my latest commit that is associated with this issue.

However, I realized another problem. It seems that the orientation of ports are updated after layout by the following line:
https://github.com/iVis-at-Bilkent/sbgnviz.js/blob/unstable/src/sbgn-extensions/sbgn-cy-instance.js#L176
I suppose that the intention here is to update them after an automated layout is run. However, when a graph is loaded by considering initial node positions ```preset``` layout is called and the same line is executed. This sometimes cause rendering ports in wrong directions. For example, for the small network represented by the SBGNML that Ludovic has attached, the orientation of ports is vertical, but it is converted to horizontal by this line. I think that an extra check can be added to see if the layout is not preset e.g. ```event.layout.options.name !== 'preset'```

**Comment by ugurdogrusoz** [comment] 2017-07-25 10:55
@leonarddrv please do the check as @metincansiper suggested so we don't perform post layout heuristics on load (when layout is preset), and assign it back to @metincansiper for verification

**Comment by leonarddrv** [comment] 2017-07-25 13:38
@metincansiper Can you verify if my change in 6cbcc9a4988c8141efffb5abd501eefc59306421 fixed this.

**Comment by metincansiper** [comment] 2017-07-26 09:39
@leonarddrv thanks seems to be solved.

**Comment by hasanbalci** [comment] 2017-07-26 10:36
@metincansiper @leonarddrv I think the extra check added in commit 6cbcc9a4988c8141efffb5abd501eefc59306421 somehow broke the 'during' layout.

**Comment by metincansiper** [comment] 2017-07-26 11:50
@hasanbalci seems to be solved by https://github.com/cytoscape/cytoscape.js-cose-bilkent/commit/c5507bb3c920714e3ef03bc3b07437685118d26b

**Comment by ugurdogrusoz** [comment] 2017-07-28 14:17
@hasanbalci please verify and close if fixed

**Closed** 2017-07-31 11:47 UTC
Labels: bug
