### ISSUE TITLE
SBML missing logic arc

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#736] opened 2024-07-15 15:24 UTC
(thanks @adrienrougny) Logic arcs are completely missed in SBML notation. These are needed to connect Species to Logical operators (see the bottom middle part [here](https://www.celldesigner.org/help/images/components42.png); edges from D & E to the logical operators are of type logic arc). PD has a counterpart for logical operators. When we implement these, we should also add the rules for creating edges of this type (Species to Logical Operators).

**Comment by ugurdogrusoz** [comment] 2024-07-17 18:08
This is from @SelbiEreshova:
Yes, indeed I did not implement a 'Logical operator arc'. Rather, I added rules so we can use existing edges (consumption, catalysis for 'and' and 'or' operator, inhibition for 'not' operator) to construct what we see in Boolean logic gate section.
Here is an 'and' operator I constructed on Newt 4:
![Screen Shot 2024-07-17 at 10 38 42](https://github.com/user-attachments/assets/5015aa86-5562-48c9-a015-117e50e91d3e)

We are still talking to find out the motivation for this but we'll properly need to disallow the usage of some arc types on logic gates when we properly implement logic arcs.

**Comment by umut-er** [comment] 2024-07-19 09:26
Where can I get the rules for logic arcs? Also, do we want the unknown logic arc?

**Comment by ugurdogrusoz** [comment] 2024-07-19 17:57
See my email and list the rules as you understand here so I can verify.

**Comment by umut-er** [comment] 2024-07-19 18:57
Here is my understanding. 

I take that modulating arcs are the second arc division in our current sbml palette. The reduced modulating arcs are the third division. 

`and` / `or` gates can take as many logic arcs as desired as input but can only have 1 output modulating (or reduced modulating) arc. `not` gate can only take in one input logic arc but otherwise is the same as the other ones.

Is that accurate @ugurdogrusoz?

PS. Maybe we should name the second division modulating arcs and the third reduced modulating arcs.

**Comment by ugurdogrusoz** [comment] 2024-07-20 01:33
Yes that sounds correct. I am not sure about naming that's why the separation without naming.

**Comment by umut-er** [comment] 2024-07-22 09:50
This issue is almost done on my part. However, there is one issue:

<img width="989" alt="image" src="https://github.com/user-attachments/assets/93474000-70b4-4703-a5a2-3b4bd0529584">

(The arcs are in the order they are in the palette) As you can see, for the majority of arcs, there is a port connection issue. This is probably because these arcs usually don't originate from a process (see the compartment on the right). However, for a minority of arcs, we get the intended behavior, which means that there is a (relatively easy?) fix out there. I think Noor should take a look at this because he was working on #735, which, from the outside, looks very similar. If these issues are unrelated, I can work on a fix.

**Comment by umut-er** [comment] 2024-07-22 10:04
Assigning to @ugurdogrusoz for now. You can check the rules for connecting logical operators and the logic arc. The port issue I outlined still remains however.

**Comment by ugurdogrusoz** [comment] 2024-07-22 20:22
@umut-er Looks good in general except:
- [ ] Logical operator --Inhibition--> Omitted process gives an error in the Console and does not work

**Comment by ugurdogrusoz** [comment] 2024-07-22 20:35
@NoorMuhammad1 Let's make sure 

- [ ] All Logical Arcs that connect a Species (Phenotype excluded) to a Logical Operator use a proper port (input port of the Logical Operator). Currently Unknown Logical Operator is the only problem one here.

- [ ] All modulation arcs listed below connect Logical Operators to their target Process nodes (Association and Dissociation excluded) from a port (output port of the Logical Operator). Currently, Unknown Catalysis and Unknown Inhibition are the only problem ones. Also (see comment below for @umut-er about constructing an Inhibition; you should test the situation with this modulation arc after that problem is fixed).
<img width="364" alt="Screenshot 2024-07-22 at 16 31 47" src="https://github.com/user-attachments/assets/d35ee400-154e-40d2-957a-39ad45a402c2">

**Comment by umut-er** [comment] 2024-07-23 07:06
> All modulation arcs listed below connect Logical Operators to their target Process nodes (Association and Dissociation excluded) from a port (output port of the Logical Operator). Currently, Unknown Catalysis and Unknown Inhibition are the only problem ones. Also (see comment below for @umut-er about constructing an Inhibition; you should test the situation with this modulation arc after that problem is fixed).

Shouldn't the reduced modulation arcs (i.e. the third group of edges, see my [message](https://github.com/iVis-at-Bilkent/newt/issues/736#issuecomment-2242548209)) also connect to the output port of the logical operator? Also, isn't there a problem with the trigger edge in the row you indicated?

> Logical operator --Inhibition--> Omitted process gives an error in the Console and does not work

Should be fixed. It was caused by a typo.

**Comment by NoorMuhammad1** [comment] 2024-07-23 10:14
I fixed both the issues. The problem was that the code looks for different types of pre-defined set of arcs to know if they should be connected at the ports or not. I just added the arcs that were missing from the list and added a new option to check for logic arc.

**Comment by ugurdogrusoz** [comment] 2024-07-23 13:37
> > All modulation arcs listed below connect Logical Operators to their target Process nodes (Association and Dissociation excluded) from a port (output port of the Logical Operator). Currently, Unknown Catalysis and Unknown Inhibition are the only problem ones. Also (see comment below for @umut-er about constructing an Inhibition; you should test the situation with this modulation arc after that problem is fixed).
> 
> Shouldn't the reduced modulation arcs (i.e. the third group of edges, see my [message](https://github.com/iVis-at-Bilkent/newt/issues/736#issuecomment-2242548209)) also connect to the output port of the logical operator? Also, isn't there a problem with the trigger edge in the row you indicated?

I think not since they are directly between Species, do not go through process nodes.

**Comment by ugurdogrusoz** [comment] 2024-07-23 14:53
3. Modulation arcs (including Unknown Catalysis and Unknown Inhibition) now connect Logical Operators from their output ports but they should not use input ports to connect to processes. This can be seen in the [related table](https://www.celldesigner.org/help/images/components42.png).
<img width="335" alt="Screenshot 2024-07-23 at 10 45 10" src="https://github.com/user-attachments/assets/8501964d-e1b1-4e08-bc58-99a1b612c638">

**Comment by NoorMuhammad1** [comment] 2024-07-31 09:48
The issue for 3. Modulation arcs connecting to ports of processes while joining logical operators with the process is solved. I added the option to check if the arc was a modulation arc and the target node was a process node. And then if it is true then the arc is not connected to the target node ports.

**Comment by ugurdogrusoz** [comment] 2024-07-31 19:37
@hasanbalci @umut-er Can you guys test this as well? Looked good to me.

**Comment by hasanbalci** [comment] 2024-07-31 22:06
I didn't see any problem either.

**Comment by umut-er** [comment] 2024-08-01 07:48
I think it is good to go.

**Closed** 2024-08-01 14:40 UTC
Labels: Critical
