### ISSUE TITLE
Tops of infoboxes are clipped

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#66] opened 2017-06-11 16:14 UTC
The top of state variables and unit of informations are slightly clipped (as seen in the first image below).
![roy](https://user-images.githubusercontent.com/7281872/27012524-cccdad60-4ed9-11e7-89a0-6aad17fae424.png)![qoy](https://user-images.githubusercontent.com/7281872/27012525-cccdee06-4ed9-11e7-8e4d-e9ebb07985b1.png)

**Comment by royludo** [comment] 2017-06-11 17:02
That gets even more obvious when you increase the border thickness.

**Comment by royludo** [comment] 2017-06-12 08:18
@ugurdogrusoz may I ask to not be assigned to this one? I have no idea where this comes from, I'm probably not the best for this problem, and it's an issue that was already there before I introduced changes. I can place infoboxes 1px down, that will hide the problem. But it will still be there when borders git thicker.

**Comment by ugurdogrusoz** [comment] 2017-06-13 11:16
Let's wait for https://github.com/iVis-at-Bilkent/newt/issues/63 to be fixed before this is fixed. @metincansiper knows how to fix it.

**Comment by ugurdogrusoz** [comment] 2017-06-29 06:41
I think we can now fix this problem (by considering border thickness for computing the rectangle for drawing refreshes) as experimented earlier

**Comment by metincansiper** [comment] 2017-06-29 07:44
After making related change I needed to compare my local build with chise daily before commiting the changes. I see that there is no problem in chise daily now. Therefore, I did not commit the changes for now. The following is a ss from chise daily.
![ekran alintisi](https://user-images.githubusercontent.com/6534865/27676662-82922d84-5cb7-11e7-9dcc-1fc061d548ed.PNG)

**Comment by ugurdogrusoz** [comment] 2017-06-29 08:51
The problem is still there in the daily. It's more obvious in AF nodes but can be reproduced in PD nodes if you increase border width:
![new_file](https://user-images.githubusercontent.com/3874988/27679376-35b04bcc-5cc1-11e7-8941-9db91f194595.png)

**Comment by metincansiper** [comment] 2017-06-29 09:37
It seems to be solved now.

**Closed** 2017-06-30 08:35 UTC
Labels: bug
