### ISSUE TITLE
Error when invalid gene name or URI is queried

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/newt#133] opened 2017-07-20 13:08 UTC
When an invalid gene name (discussed here https://github.com/iVis-at-Bilkent/newt/issues/121) or invalid URI is queried, error is thrown in console and UI becomes unresponsive.

**Comment by ugurdogrusoz** [comment] 2017-07-23 10:02
@kinimesi is this in Query dialog? duplicate of https://github.com/iVis-at-Bilkent/newt/issues/121?

**Closed** 2017-07-24 15:37 UTC
Labels: bug
