### ISSUE TITLE
Clone bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#103] opened 2017-07-03 09:03 UTC
With the default model, select and clone the synaptic button on the left. Save the model and reload. You'll see that interactions in the clone copy are connected to the original nodes, not cloned ones!
![neuronal_muscle_signalling 1 1](https://user-images.githubusercontent.com/3874988/27785825-70e4d928-5fe7-11e7-8266-4e66eac50017.png)
See Ludovic's comments in https://github.com/iVis-at-Bilkent/newt/issues/89; could they be related somehow?

**Comment by hasanbalci** [comment] 2017-07-09 06:48
Here the problem is, cloned edges have cloned source and target values in their data, but their portsource and porttarget values show the original nodes. Now, it also updates the portsource and porttarget values correctly.

**Comment by kinimesi** [comment] 2017-07-09 13:47
@hasanbalci `portsource` and `porttarget` is added to edge data by Newt, it is not something general to edges. Therefore it should not be included in clipboard extension (in other words this bug should be fixed without modifying clipboard extension).

Also your fix does not cover all cases: clone nodes which have ports, save file and load it. A similar problem arises. See the images below (from CaM-CaMK_dependent_signaling_to_the_nucleus.xml file):
**Original:**
![screen shot 2017-07-09 at 16 37 27](https://user-images.githubusercontent.com/7281872/27994393-bdccac74-64c5-11e7-9f93-21ff8034b4a8.png)
**After cloning, saving and loading:**
![screen shot 2017-07-09 at 16 36 58](https://user-images.githubusercontent.com/7281872/27994392-bd9ffbd4-64c5-11e7-8884-c81bfaf00c9b.png)

**Comment by hasanbalci** [comment] 2017-07-09 15:06
@kinimesi I think, you are right. This issue needs more consideration, but main problem is what I mentioned in above comment: portsource and porttarget values of the cloned items are not set correctly.

**Closed** 2017-07-12 10:31 UTC
Labels: bug
