### ISSUE TITLE
Saving as image does not allow to specify filename 

### ISSUE THREAD

**Issue by ivanovaos** [iVis-at-Bilkent/newt#45] opened 2017-05-03 14:13 UTC
If user tries to save the network in jpg or png format, it is saved with the name "network.png".

**Comment by ugurdogrusoz** [comment] 2017-05-04 08:55
I don't see this problem with Chrome on Windows. JPG version is saved as network.jpg correctly. Are you suggesting we should use the file name with .png or .jpg extension instead of the generic file name "network.{png,jpg}"?

**Comment by ivanovaos** [comment] 2017-05-05 13:18
@ugurdogrusoz 
What I meant is 
1) it doesn't allow us to change the filename before saving for png and jpg as it does for sbgn (see screenshot attached) 
2) doesn't use the current filename - what you've mentioned in your comment. 
I think it would be more convenient for the user to have at least 2nd option.

![screen shot 2017-05-05 at 16 14 41](https://cloud.githubusercontent.com/assets/2984700/25746867/005ace04-31ae-11e7-950c-3c0daeac1235.png)

**Comment by ugurdogrusoz** [comment] 2017-05-05 15:04
Let's go with the second option and give it a proper name without the Filename dialog to keep it simple.

**Comment by ugurdogrusoz** [comment] 2017-06-01 05:06
I don't see this fixed in this morning's build?
![image](https://cloud.githubusercontent.com/assets/3874988/26665289/41552fbe-46a1-11e7-8e16-8a75bc84f22f.png)

**Comment by leonarddrv** [comment] 2017-06-01 14:18
Previously I had only fixed the issue for .png and .jpg images

**Comment by ugurdogrusoz** [comment] 2017-06-19 11:51
Looks like save as image uses an outdated file name. Steps to reproduce:
- Start daily build, load a file from disk (say x.sbgn)
- Save as image > PNG
- The filename used is neuronal_muscle_signalling.png (default model)

Btw, we're not redundantlly maintaining file names for .sbgn, .png, and .jpg, right?

**Comment by leonarddrv** [comment] 2017-06-19 13:46
No, we don't redundantly maintain many file names.
I actually got the filenames during the load part, but it seems that I was just checking for loading of samples.

**Comment by ugurdogrusoz** [comment] 2017-06-19 13:53
I am confused. If you load a file from disk and then do one of the following:
- save
- save as image
you will be prompted with 2 different file names (former is correctly the current model name; the latter is the one before the load)

**Comment by leonarddrv** [comment] 2017-06-19 14:11
It was a mistake I did while defining the filename.
It should be fixed now.

**Closed** 2017-06-20 06:27 UTC
Labels: enhancement
