### ISSUE TITLE
Adding a complex breaks subunit connection rule

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#33] opened 2017-03-29 10:53 UTC
Subunits of a complex are not allowed to have any edges connected. Only the complex itself can have connections. When creating a complex from nodes that have edges (from Edit > Add Complex), those edges are preserved. Thus, we end up with a rule violation. The same problem arises when moving nodes in complex with ctrl+drag.

We should completely remove the edges upon inclusion in a complex.

**Comment by ugurdogrusoz** [comment] 2017-03-29 14:38
Looks like our complex members are allowed to have edges even without a complex scenario as above!

**Comment by royludo** [comment] 2017-03-29 17:44
@ugurdogrusoz  Really ? Now that's not normal... How and where were you able to add edges ?

**Comment by ugurdogrusoz** [comment] 2017-03-29 18:25
To reproduce simple add a substrate edge from myosin in myosin-ATP complex to the dissociation in the default model

**Comment by royludo** [comment] 2017-03-29 18:43
I think chise hasn't been updated for the daily app.

**Comment by ugurdogrusoz** [comment] 2017-03-30 06:30
You're right today's daily will not allow such edges. I didn't realize there was a recent fix. So, it's only when things are added through the menu. I think we have two choices (as opposed to removing edges connected to members upon creation of a parent complex): 1) connect those edges to the parent (change source/target from member to parent) 2) do not allow creation of the complex.
I am for 1) but we could discuss.

**Comment by ugurdogrusoz** [comment] 2017-07-07 07:29
Another case where it's broken is when a node is transferred into a complex.
Let's not allow both scenarios at all.

**Closed** 2017-07-10 08:50 UTC
Labels: bug
