### ISSUE TITLE
Inferring parents from geometry on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#176] opened 2017-08-28 08:19 UTC
I am pretty sure we used to do it like this but that seems not to be the case any longer. I think we should have an option (true by default) that does this.

**Comment by kinimesi** [comment] 2017-08-28 10:03
@ugurdogrusoz we still do it. Try the attached files below (`compartmentRef` is removed).
[transforming_growth_factor_beta_signaling_pathway.txt](https://github.com/iVis-at-Bilkent/newt/files/1256404/transforming_growth_factor_beta_signaling_pathway.txt)
[neuronal_muscle_signaling-no-compartmentRef.txt](https://github.com/iVis-at-Bilkent/newt/files/1256403/neuronal_muscle_signaling-no-compartmentRef.txt)

Duplicate of https://github.com/iVis-at-Bilkent/chise.js/issues/75

**Comment by ugurdogrusoz** [comment] 2017-08-28 11:14
@kinimesi But when I query PC, returned complexes aren't modeled as parents of their members. E.g. Paths between BRCA1 and BRCA2

**Comment by ugurdogrusoz** [comment] 2017-08-28 11:24
@kinimesi you're right it does normally infer parents on load. Doesn't the load of the result of a PC query go through the same code?

**Comment by kinimesi** [comment] 2017-08-28 12:22
We assign parents based on geometry only for compartments. Complexes are saved in a different way than compartments. Below is how the complexes with children should be saved:
```xml
    <glyph id="_1129b8c7-71da-4a6c-8681-3082e6f04a6c" class="complex" >
      <label text="myosin"/>
      <bbox x="1118.3605112995508" y="83.60247044730838" w="73.25" h="81.7"/>
      <glyph id="_5fcbfc9c-92a0-45b2-834b-ad8866d4008b" class="simple chemical">
        <label text="ATP"/>
        <bbox x="1119.9855112995508" y="128.67747044730837" w="35" h="35"/>
      </glyph>
    </glyph>
```

And this is how they are saved in PathwayCommons (or other databases which save it in wrong format):
```xml
    <glyph id="_1129b8c7-71da-4a6c-8681-3082e6f04a6c" class="complex" >
      <label text="myosin"/>
      <bbox x="1118.3605112995508" y="83.60247044730838" w="73.25" h="81.7"/>
    </glyph>
    <glyph id="_5fcbfc9c-92a0-45b2-834b-ad8866d4008b" class="simple chemical">
        <label text="ATP"/>
        <bbox x="1119.9855112995508" y="128.67747044730837" w="35" h="35"/>
    </glyph>
```

I think this needs to be solved in PathwayCommons SBGNML converter. Doing it in SBGNViz will be very inefficient and make the loading time much slower (which is slow already).

**Comment by ugurdogrusoz** [comment] 2017-08-28 12:23
@kinimesi 👍

**Comment by IgorRodchenkov** [comment] 2017-09-08 17:03
Please double-check - see BioPAX/Paxtools#33 
It can be that the ATP (glyph) above is not in fact a member of that 'myosin' complex...
If in doubt, please provide more details - the PC URL query - the BioPAX result and corresponding SBGN result, and the ID(s) of problematic complexes/glyphs, if any.

**Comment by ugurdogrusoz** [comment] 2017-09-14 07:26
@kinimesi I have done some further investigation. I tried the following query:
http://www.pathwaycommons.org/pc2/graph?source=P20908&kind=PATHSBETWEEN&format=SBGN
and uploaded the resulting SBGNML in Newt. Complexes are specified correctly (members nested inside their parents); yet Newt shows them as if they aren't inside parent Complexes. For instance, look at the complex with label "PLOD2:Fe2+ dimer".

**Comment by ugurdogrusoz** [comment] 2017-09-26 12:31
Looks like the problem here is that a complex member A, which is inside a complex B, which in turn is inside a compartment C has a compartmentRef to A, which is throwing our read off.

**Comment by ugurdogrusoz** [comment] 2017-09-27 15:15
Since SBGN allows different members of a complex to belong to different compartments but in our compound graph model, we don't allow such nesting (only proper hierarchy), I guess the best way to handle this is to ignore "compartmentRef"s of complex members since their parent will end up to be the parent complex anyway.

**Comment by royludo** [comment] 2017-09-28 19:50
I'm not 100% sure SBGN allows such behavior, it seems really weird to me.  Ignoring it as you said might be the safest and most logical way indeed.

**Comment by ugurdogrusoz** [comment] 2017-09-29 05:53
@royludo I am pretty sure it does. One member of a complex belongs to extra-cellular, other to cytosol, for instance.

**Comment by royludo** [comment] 2017-09-29 07:37
@ugurdogrusoz you're right. I checked and it is allowed, for lack of a better solution to represent macromolecules spanning several compartments. That's really not ideal...

**Closed** 2017-10-06 12:30 UTC
Labels: duplicate, enhancement
