### ISSUE TITLE
Only reversible should break map type PD

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/newt#305] opened 2018-06-14 08:27 UTC
Among the reactions created from the template, only the reversible one should change the map type to Unknown, not Association and Dissociation.

**Comment by kaansancak** [comment] 2018-06-14 11:53
It seems like it is not a bug. When a new graph is first created it's map type is unknown. If we add a reaction from template, it does not modify the map type.

-  Create a new graph. -> Map type is unknown.
- Add a macromolecule. -> Map type is PD.
- Add a reaction from template. -> Map type is PD.

-  Create a new graph. -> Map type is unknown.
- Add a reaction from template. -> Map type is unkown.
- Add a macromolecule. -> Map type is PD.

**Comment by kaansancak** [comment] 2018-06-14 12:11
It should be fixed now.

**Closed** 2018-06-14 12:55 UTC
Labels: bug
