### ISSUE TITLE
Clone markers don't match some shapes

### ISSUE THREAD

**Issue by royludo** [iVis-at-Bilkent/newt#191] opened 2017-10-26 08:59 UTC
The clone marker area behaves weirdly on complex, simple chemical, unspecified entity and perturbing agents shapes. This depends on the size of the parent shape.

![image](https://user-images.githubusercontent.com/7210995/32044028-b55f449e-ba3c-11e7-8df1-d363a1dc1413.png)

**Comment by ugurdogrusoz** [comment] 2017-11-14 11:12
@royludo Looks like this is happening when node are very narrow (width < 45 for complexes, < 35 for simple chemicals) but cannot reproduce for perturbing agent and unspecified entity though?

**Comment by royludo** [comment] 2017-11-14 14:36
@ugurdogrusoz I just tested on chrome, safari and firefox, it does that only on firefox (for the perturbing agent and simple chemical)

**Comment by gokberkkaraca** [comment] 2018-06-04 14:05
This issue is solved by [5972d8b](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/5972d8b3ebee296b4d854cb6cc810dd0e194aeb8) and [c440c9bf](https://github.com/iVis-at-Bilkent/sbgnviz.js/commit/c440c9bfde2dd2000d73e0679326b2c0882492de), Firefox issue still remains.

**Comment by ugurdogrusoz** [comment] 2019-06-21 12:37
Remaining issue is quite marginal and won't be fixed. If there is a specific request for it, we'll reconsider.

**Closed by ugurdogrusoz** 2019-06-21 12:37 UTC
Labels: Viewer as well, wontfix
